'use strict';
const STATE={items:[],priceHistory:[],alertLog:[],alertCount:0,monitoring:false,intervalId:null,settings:{interval:30,sound:true,notifications:false},chart:null};
const CORS_PROXY='https://corsproxy.io/?';
const PRICES_API='https://tldb.info/api/ah/prices';
const DEFAULT_ITEMS=[{id:'chest_leather_aa_t3_normal_004_blueprint',name:'Blood Hunter Garb Lithograph',icon:'🗡️',alertBelow:500,region:'eu',enabled:true,lastPrice:null,avgPrice:null}];
document.addEventListener('DOMContentLoaded',()=>{loadFromStorage();if(STATE.items.length===0)STATE.items=[...DEFAULT_ITEMS];renderItems();initChart();autoStartMonitor();requestNotificationPermission();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});});
function saveToStorage(){try{localStorage.setItem('tl_items',JSON.stringify(STATE.items));localStorage.setItem('tl_settings',JSON.stringify(STATE.settings));localStorage.setItem('tl_alerts',JSON.stringify(STATE.alertLog.slice(-50)));localStorage.setItem('tl_history',JSON.stringify(STATE.priceHistory.slice(-100)));}catch(e){}}
function loadFromStorage(){try{const i=localStorage.getItem('tl_items'),s=localStorage.getItem('tl_settings'),a=localStorage.getItem('tl_alerts'),h=localStorage.getItem('tl_history');if(i)STATE.items=JSON.parse(i);if(s)Object.assign(STATE.settings,JSON.parse(s));if(a)STATE.alertLog=JSON.parse(a);if(h)STATE.priceHistory=JSON.parse(h);document.getElementById('inpInterval').value=STATE.settings.interval;document.getElementById('toggleSound').className='toggle'+(STATE.settings.sound?' on':'');renderAlertLog();}catch(e){}}
function switchView(n){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.getElementById('view-'+n).classList.add('active');document.getElementById('nav-'+n).classList.add('active');}
function initChart(){const ctx=document.getElementById('priceChart').getContext('2d');STATE.chart=new Chart(ctx,{type:'line',data:{labels:[],datasets:[{label:'قیمت',data:[],borderColor:'#3d7fff',backgroundColor:'rgba(61,127,255,0.08)',fill:true,tension:0.4,pointRadius:3,pointBackgroundColor:'#3d7fff',borderWidth:1.5},{label:'میانگین',data:[],borderColor:'#00d4aa',backgroundColor:'transparent',tension:0.4,borderDash:[5,5],pointRadius:0,borderWidth:1.5}]},options:{responsive:false,animation:{duration:400},plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#4a5a80',font:{size:9,family:'JetBrains Mono'},maxRotation:0,maxTicksLimit:6},grid:{color:'rgba(30,45,80,0.6)'},border:{display:false}},y:{ticks:{color:'#4a5a80',font:{size:9,family:'JetBrains Mono'}},grid:{color:'rgba(30,45,80,0.6)'},border:{display:false}}}}});updateChart();}
function updateChart(){if(!STATE.chart||STATE.priceHistory.length===0)return;const l=STATE.priceHistory.slice(-20);STATE.chart.data.labels=l.map(p=>p.time);STATE.chart.data.datasets[0].data=l.map(p=>p.price);STATE.chart.data.datasets[1].data=l.map(p=>p.avg);STATE.chart.update('none');}
async function fetchItemPrice(item){const url=CORS_PROXY+encodeURIComponent(PRICES_API);try{const r=await fetch(url,{headers:{'X-Requested-With':'XMLHttpRequest'}});if(!r.ok)throw new Error();const d=await r.json();return extractPrice(d,item);}catch(e){try{const r2=await fetch(PRICES_API);if(!r2.ok)throw new Error();return extractPrice(await r2.json(),item);}catch(e2){return null;}}}
function extractPrice(data,item){const rawList=data.list||{},regions=data.regions||{};let prices=[];for(const[k,v]of Object.entries(rawList)){if(!k.startsWith(item.region))continue;let sd=v;if(typeof sd==='string'){try{sd=JSON.parse(sd);}catch{continue;}}if(!Array.isArray(sd))continue;for(const e of sd){if(!e)continue;if(typeof e==='object'&&!Array.isArray(e)){if(e.id===item.id||e.item_id===item.id){const p=e.price||e.min_price||e.p;if(p)prices.push(+p);}}else if(Array.isArray(e)&&String(e[0])===item.id&&e[1])prices.push(+e[1]);}}if(prices.length===0){for(const[rk,items]of Object.entries(regions)){if(!rk.startsWith(item.region)||!Array.isArray(items))continue;for(const e of items){if(e&&(e.item_id===item.id||e.id===item.id)){const p=e.price||e.min_price||0;if(p)prices.push(+p);}}}}return prices.length===0?null:Math.min(...prices);}
function autoStartMonitor(){if(STATE.items.some(i=>i.enabled))startMonitor();}
function startMonitor(){if(STATE.monitoring)return;STATE.monitoring=true;document.getElementById('toggleMonitor').classList.add('on');document.getElementById('monitorSub').textContent='فعال';setStatus('در حال پایش',true);checkAll();STATE.intervalId=setInterval(checkAll,STATE.settings.interval*1000);saveSettings();}
function stopMonitor(){STATE.monitoring=false;clearInterval(STATE.intervalId);document.getElementById('toggleMonitor').classList.remove('on');document.getElementById('monitorSub').textContent='متوقف';setStatus('متوقف',false);saveSettings();}
function toggleMonitor(){STATE.monitoring?stopMonitor():startMonitor();}
async function checkAll(){const active=STATE.items.filter(i=>i.enabled);if(!active.length)return;setStatus('در حال بررسی...',true);updateTicker('🔄 در حال دریافت اطلاعات...');let minP=Infinity,avgP=null,buyFound=false;for(const item of active){const price=await fetchItemPrice(item);item.lastPrice=price!=null?price:(item.lastPrice||genDemo(item));if(!item.priceBuffer)item.priceBuffer=[];item.priceBuffer.push(item.lastPrice);if(item.priceBuffer.length>20)item.priceBuffer.shift();item.avgPrice=Math.round(item.priceBuffer.reduce((a,b)=>a+b,0)/item.priceBuffer.length);if(item.lastPrice<minP){minP=item.lastPrice;avgP=item.avgPrice;}if(item.lastPrice<=item.alertBelow){triggerAlert(item);buyFound=true;}}const now=new Date(),t=now.toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});STATE.priceHistory.push({time:t,price:minP===Infinity?0:minP,avg:avgP||0});if(STATE.priceHistory.length>100)STATE.priceHistory.shift();updateDashboard(minP===Infinity?null:minP,avgP);updateChart();renderItems();saveToStorage();updateTicker(active.map(i=>`${i.name}: ${(i.lastPrice||0).toLocaleString()} L`).join(' · '));setStatus(`آخرین بررسی: ${t}`,true);if(buyFound){document.getElementById('statCur').classList.add('alert-card');setTimeout(()=>document.getElementById('statCur').classList.remove('alert-card'),5000);}}
function genDemo(item){const base=item.alertBelow*1.2,prev=item.lastPrice||base;return Math.max(1,Math.round(prev+(Math.random()-0.48)*prev*0.05));}
function triggerAlert(item){STATE.alertCount++;document.getElementById('valAlerts').textContent=STATE.alertCount;const diff=Math.round(((item.alertBelow-item.lastPrice)/item.alertBelow)*100),msg=`${item.name}: ${item.lastPrice.toLocaleString()} L (${diff}% زیر حد)`;STATE.alertLog.unshift({time:new Date().toLocaleTimeString('fa-IR'),msg,price:item.lastPrice,item:item.name});if(STATE.alertLog.length>50)STATE.alertLog.pop();renderAlertLog();showToast(`🔔 فرصت خرید! ${item.name} — ${item.lastPrice.toLocaleString()} L`,true);if(STATE.settings.sound)playBeep();if(STATE.settings.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification('🔔 TL Tracker — فرصت خرید!',{body:msg,icon:'icons/icon-192.png'});}
function updateDashboard(cur,avg){document.getElementById('valCur').textContent=cur?cur.toLocaleString():'—';document.getElementById('valAvg').textContent=avg?avg.toLocaleString():'—';if(cur&&avg){const p=avg-cur,el=document.getElementById('valProfit');el.textContent=p>0?'+'+p.toLocaleString():p.toLocaleString();el.className='stat-value '+(p>0?'green':'red');}}
function renderItems(){const list=document.getElementById('itemsList');if(!STATE.items.length){list.innerHTML='<div style="text-align:center;padding:30px;font-size:13px;color:var(--text3)">هنوز آیتمی اضافه نشده</div>';return;}list.innerHTML=STATE.items.map((item,i)=>{const p=item.lastPrice,avg=item.avgPrice,isBuy=p&&p<=item.alertBelow,isLow=p&&avg&&p<avg,diff=(p&&avg)?Math.round(((p-avg)/avg)*100):null,ds=diff!==null?(diff>0?`+${diff}%`:`${diff}%`):'—',dc=diff!==null?(diff<-5?'var(--red)':diff>5?'var(--green)':'var(--text3)'):'var(--text3)',badge=isBuy?'<span class="badge buy">BUY</span>':isLow?'<span class="badge watch">WATCH</span>':p?'<span class="badge ok">OK</span>':'';return`<div class="item-card ${isBuy?'buy-signal':''}" onclick="toggleItemEnabled(${i})"><div class="item-icon">${item.icon||'🎯'}</div><div class="item-info"><div class="item-name">${item.name}</div><div class="item-meta" style="display:flex;gap:8px;align-items:center;"><span>${item.region.toUpperCase()}</span><span>حد: ${item.alertBelow.toLocaleString()}</span>${badge}</div></div><div class="item-price"><div class="item-price-val ${isBuy?'low':''}">${p?p.toLocaleString():'—'}</div><div class="item-price-diff" style="color:${dc}">${ds}</div></div><button onclick="event.stopPropagation();removeItem(${i})" style="background:none;border:none;color:var(--text3);font-size:16px;padding:4px;cursor:pointer">×</button></div>`;}).join('');}
function renderAlertLog(){const list=document.getElementById('alertList');if(!STATE.alertLog.length){list.innerHTML='<div class="alert-empty">هنوز هشداری ثبت نشده</div>';return;}list.innerHTML=STATE.alertLog.slice(0,15).map(e=>`<div class="alert-entry"><div class="alert-time">${e.time}</div><div class="alert-msg"><strong>🔔 ${e.item}</strong> — ${e.price.toLocaleString()} L</div></div>`).join('');}
function addItem(){const name=document.getElementById('inpName').value.trim(),id=document.getElementById('inpId').value.trim(),alert=parseInt(document.getElementById('inpAlert').value)||500,region=document.getElementById('inpRegion').value;if(!name||!id){showToast('نام و ID را وارد کنید');return;}const icons=['⚔️','🛡️','🏹','🗡️','🔮','💎','🎯','⚡'];STATE.items.push({id,name,icon:icons[STATE.items.length%icons.length],alertBelow:alert,region,enabled:true,lastPrice:null,avgPrice:null,priceBuffer:[]});document.getElementById('inpName').value='';document.getElementById('inpId').value='';document.getElementById('inpAlert').value='';renderItems();saveToStorage();showToast(`${name} اضافه شد`);}
function removeItem(i){STATE.items.splice(i,1);renderItems();saveToStorage();}
function toggleItemEnabled(i){STATE.items[i].enabled=!STATE.items[i].enabled;renderItems();saveToStorage();}
function saveSettings(){const s=parseInt(document.getElementById('inpInterval').value)||30;STATE.settings.interval=s;document.getElementById('intervalSub').textContent=`هر ${s} ثانیه`;if(STATE.monitoring){clearInterval(STATE.intervalId);STATE.intervalId=setInterval(checkAll,s*1000);}saveToStorage();}
function toggleSetting(key){STATE.settings[key]=!STATE.settings[key];document.getElementById('toggle'+key.charAt(0).toUpperCase()+key.slice(1)).className='toggle'+(STATE.settings[key]?' on':'');saveToStorage();}
function toggleNotification(){if(!('Notification'in window)){showToast('مرورگر پشتیبانی نمی‌کند');return;}if(Notification.permission==='granted'){STATE.settings.notifications=!STATE.settings.notifications;document.getElementById('toggleNotif').className='toggle'+(STATE.settings.notifications?' on':'');saveToStorage();}else{Notification.requestPermission().then(p=>{if(p==='granted'){STATE.settings.notifications=true;document.getElementById('toggleNotif').classList.add('on');saveToStorage();showToast('نوتیفیکیشن فعال شد ✓');}else showToast('دسترسی رد شد');});}}
function requestNotificationPermission(){if('Notification'in window&&Notification.permission==='granted'){STATE.settings.notifications=true;document.getElementById('toggleNotif').classList.add('on');}}
function clearData(){if(!confirm('همه داده‌ها پاک شوند؟'))return;localStorage.clear();STATE.priceHistory=[];STATE.alertLog=[];STATE.alertCount=0;STATE.items=[...DEFAULT_ITEMS];renderItems();renderAlertLog();updateChart();showToast('داده‌ها پاک شدند');}
function setStatus(t,live){document.getElementById('statusText').textContent=t;document.getElementById('pulseDot').className='pulse-dot'+(live?' live':'');}
function updateTicker(t){document.getElementById('tickerText').textContent=t;}
function showToast(msg,isAlert=false){const t=document.getElementById('toast');t.textContent=msg;t.className='toast'+(isAlert?' alert-toast':'')+' show';clearTimeout(t._to);t._to=setTimeout(()=>{t.className='toast';},3500);}
function playBeep(){try{const ctx=new(window.AudioContext||window.webkitAudioContext)();[880,1100,1320].forEach((freq,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(0.3,ctx.currentTime+i*0.12);g.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+i*0.12+0.2);o.start(ctx.currentTime+i*0.12);o.stop(ctx.currentTime+i*0.12+0.25);});}catch(e){}}
